easy_admin:
    design:
        brand_color: '#1ABC9C'
    entities:
        
        Ticket:
            class: Blox\TicketBundle\Entity\Ticket

            

            form:
                fields:
                    - { property: 'descripcion', label: 'Descripcion' }
                    - { property: 'tipo', label: 'Tipo' }
                    - { property: 'categoria', label: 'Categoria' }
                    - { property: 'nivel', label: 'Nivel' }
                    - { property: 'estado', label: 'Estado' }
                    - { property: 'empresa', label: 'Empresa' }


        Categoria:
            class: Blox\TicketBundle\Entity\Categoria
            #controller: Blog\BlogBundle\Controller\PostController
            form:
                fields:
                    - { property: 'categoria', label: 'Categoria' }
            list:
                fields:
                    - { property: 'Categoria' }
                    - { property: 'Tickets' }

                actions: 
                        - { name: 'edit', label: 'Editar', title: 'Edit', icon: 'pencil' }
                        - { name: 'delete', label: 'Eliminar', icon: 'trash'}
                        - { name: 'new', label: 'Crear Categoria', icon: 'plus'}
                        - { name: 'search', label: 'Buscar', icon: 'search'}
                    
        Tipo:
            class: Blox\TicketBundle\Entity\Tipo

            form:
                fields:
                    - { property: 'tipo', label: 'Tipo' }
           
            list:
                fields:
                    - 'Tipo' 
                    - 'Tickets'

        Estado:
            class: Blox\TicketBundle\Entity\Estado

            form:
                fields:
                    - { property: 'estado', label: 'Estado' }
           
            list:
                fields:
                    - 'Estado' 
                    - 'Tickets'

        Nivel:
            class: Blox\TicketBundle\Entity\Nivel

            form:
                fields:
                    - { property: 'nivel', label: 'Nivel' }
           
            list:
                fields:
                    - 'Nivel' 
                    - 'Tickets'

        User:
            class: Blox\TicketBundle\Entity\User

        Empresa:
            class: Blox\TicketBundle\Entity\Empresa

            form:
                fields:
                    - { property: 'empresa', label: 'Empresa' }
           
            list:
                fields:
                    - 'Empresa' 
                    - 'Tickets'