easy_admin:
    design:
        brand_color: '#1ABC9C'
        form_theme: 'vertical'
    entities:
        
        Ticket:
            class: Blox\TicketBundle\Entity\Ticket
            controller: Blox\TicketBundle\Controller\TicketController
            form:
                fields:
                    - { property: 'tipo', label: 'Tipo' }
                    - { property: 'categoria', label: 'Categoria' }
                    - { property: 'nivel', label: 'Nivel' }
                   # - { property: 'estado', label: 'Estado' }
                    - { property: 'empresa', label: 'Empresa' }
                    - { property: 'descripcion', label: 'Descripción', type: 'textarea' }

            edit:
                fields:
                    - { property: 'tipo', label: 'Tipo',  css_class: 'col-md-2', type_options: { disabled: true } }
                    - { property: 'categoria', label: 'Categoria',  css_class: 'col-md-3', type_options: { disabled: true } }
                    - { property: 'nivel', label: 'Nivel',  css_class: 'col-md-2', type_options: { disabled: true } }
                    - { property: 'estado', label: 'Estado', css_class: 'col-md-2 hidden', type_options: { disabled: true } }
                    - { property: 'empresa', label: 'Empresa', css_class: 'col-md-3', type_options: { disabled: true } }
                    - { property: 'descripcion', label: 'Descripción', css_class: 'col-md-6', type: 'textarea', type_options: { disabled: true } }
                    - { property: 'respuesta', label: 'Respuesta', css_class: 'col-md-6', type: 'textarea' }
                actions: 
                    - { name: 'ticket_success', type: 'route', icon: 'eye', label: 'Aceptar', role: 'button', css_class: 'pull-right btn btn-success'}
                    - { name: 'ticket_rejected', type: 'route', icon: 'eye', label: 'Rechazar', role: 'button', css_class: 'pull-left btn btn-danger'}
                    - { name: 'delete', css_class: 'btn btn-info hidden'}
                    - { name: 'edit', css_class: 'btn btn-info hidden', type: 'submit', role: 'button'}

            show:                                           
                fields:
                - { property: 'categoria', label: 'Categoria' }
                - { property: 'tipo', label: 'Tipo' }
                - { property: 'nivel', label: 'Nivel' }
                - { property: 'created_at', type: 'date', label: 'Creado' }
                - { property: 'estado', label: 'Estado' }
                - { property: 'descripcion', label: 'Descripcion' }

                actions:
                     - { name: 'ticket_verified', type: 'route', icon: 'undo', label: 'Volver al listado', role: 'button' }
                     - { name: 'delete', css_class: 'btn btn-info hidden'}  
                     - { name: 'list', css_class: 'btn btn-info hidden'} 
                     - { name: 'edit', css_class: 'btn btn-info hidden'} 

            list:
                fields:
                - { property: 'id', label: '#ID' }
                - { property: 'descripcion', label: 'Descripcion' }
                - { property: 'tipo', label: 'Tipo' }
                - { property: 'categoria', label: 'Categoria' }
                - { property: 'nivel', label: 'Nivel' }
<<<<<<< HEAD
                - { property: 'tiempoRespuesta', label: 'Tiempo de respuesta', type_options: { class: 'Blox\TicketBundle\Entity\Nivel' } }
=======
                - { property: 'tiempoRespuesta', label: 'Tiempo de respuesta' }
>>>>>>> 83cc643a682e6e606394482658fbe005dac3ce70
                - { property: 'estado', label: 'Estado' }
                - { property: 'empresa', label: 'Empresa' }
                actions:
                    - { name: 'show', icon: 'eye', label: 'Ver', role: 'button' }
                    - { name: 'delete', icon: 'trash', label: 'Eliminar' }
                    - { name: 'edit', icon: 'pencil', label: 'Editar' }
                    #- { name: 'search', icon: 'search', label: 'Buscar' }
                    - { name: 'new', icon: 'plus', label: 'Nuevo' }
                    #- { name: 'list.row_actions', label: 'Acciones'}
             
            

            list:
                actions: ['Ver']



        Categoria:
            class: Blox\TicketBundle\Entity\Categoria
            #controller: Blog\BlogBundle\Controller\PostController
            form:
                fields:
                    - { property: 'categoria', label: 'Categoria' }
            list:
                fields:
                    - { property: 'categoria' }
                    - { property: 'tickets', class: '' }

                actions: 
                        - { name: 'edit', label: 'Editar', title: 'Edit', icon: 'pencil' }
                        - { name: 'delete', label: 'Eliminar', icon: 'trash'}
                        - { name: 'new', label: 'Crear Categoria', icon: 'plus'}
                        - { name: 'search', label: 'Buscar', icon: 'search'}
                    
        Tipo:
            class: Blox\TicketBundle\Entity\Tipo

            form:
                fields:
                    - { property: 'tipo', label: 'Tipo' }
           
            list:
                fields:
                    - 'tipo' 
                    - 'tickets'

        Estado:
            class: Blox\TicketBundle\Entity\Estado

            form:
                fields:
                    - { property: 'estado', label: 'Estado' }
           
            list:
                fields:
                    - 'estado' 
                    - 'tickets'

        Nivel:
            class: Blox\TicketBundle\Entity\Nivel

            form:
                fields:
                    - { property: 'nivel', label: 'Nivel' }
           
            list:
                fields:
                    - 'nivel' 
                    - 'tickets'
<<<<<<< HEAD
                    - tiempoRespuesta
=======
                    - 'tiempoRespuesta'
>>>>>>> 83cc643a682e6e606394482658fbe005dac3ce70

        User:
            class: Blox\TicketBundle\Entity\User

        Empresa:
            class: Blox\TicketBundle\Entity\Empresa

            form:
                fields:
                    - { property: 'empresa', label: 'Empresa' }
           
            list:
                fields:
                    - 'empresa' 
                    - 'tickets'