easy_admin:
    design:
        brand_color: '#1ABC9C'
        form_theme: 'vertical'
    entities:
        
        Ticket:
            class: Blox\TicketBundle\Entity\Ticket
            
            form:
                fields:
                    - { property: 'tipo', label: 'Tipo' }
                    - { property: 'categoria', label: 'Categoria' }
                    - { property: 'nivel', label: 'Nivel' }
                    - { property: 'estado', label: 'Estado' }
                    - { property: 'empresa', label: 'Empresa' }
                    - { property: 'descripcion', label: 'Descripción', type: 'textarea' }
            list:
                fields:
                - { property: 'id', label: '#ID' }
                - { property: 'descripcion', label: 'Descripcion' }
                - { property: 'tipo', label: 'Tipo' }
                - { property: 'categoria', label: 'Categoria' }
                - { property: 'nivel', label: 'Nivel' }
                - { property: 'estado', label: 'Estado' }
                - { property: 'empresa', label: 'Empresa' }
                actions:
                    - { name: 'show', icon: 'eye', label: 'Ver', role: 'button' }
                    - { name: 'delete', icon: 'trash', label: 'Eliminar' }
                    - { name: 'edit', icon: 'pencil', label: 'Editar' }
                    #- { name: 'search', icon: 'search', label: 'Buscar' }
                    - { name: 'new', icon: 'plus', label: 'Nuevo' }
                    #- { name: 'list.row_actions', label: 'Acciones'}
             
            show:
                fields:
                - { property: 'categoria', label: 'Categoria' }
                - { property: 'tipo', label: 'Tipo' }
                - { property: 'nivel', label: 'Nivel' }
                - { property: 'created_at', type: 'date', label: 'Creado' }
                - { property: 'estado', label: 'Estado' }
                - { property: 'descripcion', label: 'Descripcion' }


        Categoria:
            class: Blox\TicketBundle\Entity\Categoria
            #controller: Blog\BlogBundle\Controller\PostController
            form:
                fields:
                    - { property: 'categoria', label: 'Categoria' }
            list:
                fields:
                    - { property: 'categoria' }
                    - { property: 'tickets', class: '' }

                actions: 
                        - { name: 'edit', label: 'Editar', title: 'Edit', icon: 'pencil' }
                        - { name: 'delete', label: 'Eliminar', icon: 'trash'}
                        - { name: 'new', label: 'Crear Categoria', icon: 'plus'}
                        - { name: 'search', label: 'Buscar', icon: 'search'}
                    
        Tipo:
            class: Blox\TicketBundle\Entity\Tipo

            form:
                fields:
                    - { property: 'tipo', label: 'Tipo' }
           
            list:
                fields:
                    - 'tipo' 
                    - 'tickets'

        Estado:
            class: Blox\TicketBundle\Entity\Estado

            form:
                fields:
                    - { property: 'estado', label: 'Estado' }
           
            list:
                fields:
                    - 'estado' 
                    - 'tickets'

        Nivel:
            class: Blox\TicketBundle\Entity\Nivel

            form:
                fields:
                    - { property: 'nivel', label: 'Nivel' }
           
            list:
                fields:
                    - 'nivel' 
                    - 'tickets'

        User:
            class: Blox\TicketBundle\Entity\User

        Empresa:
            class: Blox\TicketBundle\Entity\Empresa

            form:
                fields:
                    - { property: 'empresa', label: 'Empresa' }
           
            list:
                fields:
                    - 'empresa' 
                    - 'tickets'